#*
    This is a standard library for BlueScript 2.0
    this library is designed to be used for posix
    based commands
*#
#use libs/asm/posix.asm
#use libs/asm/bs_fstream.asm
#include libs/string.bs

const str os_name "posix"

const int SUCCESS_EXIT 0
const int FAILED_EXIT 1

block pwarn str -> void
    err
    print err
end

block perr str -> void
    msg
    pwarn msg
    exit FAILED_EXIT
end

block exit int -> void
    exitCode
    bs_asmExit exitCode
end