
#use libs/asm/posix.asm
#use libs/asm/bs_fstream.asm
#include libs/string.bs

const str os_name "posix"

const int SUCCESS_EXIT 0
const int FAILED_EXIT 1

const int SYS_EXECVE 59

block pwarn str -> void
    err
    print err
end

block perr str -> void
    msg
    pwarn msg
    exit FAILED_EXIT
end

block exit int -> void
    exitCode
    bs_asmExit exitCode
end

block exec str str
    cmd argv
    syscall SYS_EXECVE cmd argv 0
    pop
end